import { ModeToggle } from "@/components/app-theme-toggle";
import { Metadata } from "next";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Hakhiros 2 | Calculate",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
      <main className="w-full h-screen overflow-hidden">
        <div className="flex items-center justify-end p-2">
          <ModeToggle />
        </div>
        {children}
      </main>
    </SessionProvider>
  );
}
