import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AppBlob } from "@/components/app-blob";
import { Toaster } from "@/components/ui/toaster";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Reclimate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  h-screen`}
      >
        <AppBlob x={200} y={-100} />
        <AppBlob x={-300} y={0} bottom />
        <AppBlob side="right" x={10} y={10} bottom />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
